version: '3.8'
name: anon-vote-dev

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-app_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - server-net

  cache:
    image: redis:8.2.0
    restart: unless-stopped
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - server-net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      - server-net

  app:
    build:
      context: ../..
      dockerfile: docker/dev/dev.Dockerfile
      args:
        WATCH_EXEC_DOWNLOAD: ${WATCH_EXEC_DOWNLOAD}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_started
    environment:
      APP_PORT: ${APP_PORT}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      WATCH_EXEC_DOWNLOAD: ${WATCH_EXEC_DOWNLOAD}
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: ${JAVA_OPTS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      - ../../src:/app/src:rw
      - ../../pom.xml:/app/pom.xml:rw
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "5005:5005"
    networks:
      - server-net

volumes:
  postgres_data:
  redis_data:
  maven-repo:

networks:
  server-net:
    driver: bridge