server:
  port: ${APP_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      pool-name: poll-pool
      maximum-pool-size: 10
      connection-timeout: 5000

  jpa:
    show-sql: true
    open-in-view: false

    hibernate:
      format_sql: true
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

  devtools:
    restart:
      enabled: true
      poll-interval: 1000
      quiet-period: 400

  task:
    execution:
      pool:
        core-size: 5
        max-size: 20

springdoc:
  api-docs:
    path: '/api-doc'
  swagger-ui:
    path: '/swagger-ui'

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
#    org.modelmapper: DEBUG
#    org.hibernate.SQL: DEBUG

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  from: ${MAIL_FROM_ADDRESS}