version: '3.8'
name: anon-vote

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    read_only: true
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-app_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - server-net

  cache:
    image: redis:8.2.0
    restart: unless-stopped
    read_only: true
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    read_only: true
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-p@x128.ru}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-123123}
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      - server-net

  app:
    build:
      context: ../..
      dockerfile: docker/dev/prod.Dockerfile
    restart: unless-stopped
    read_only: true
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USER: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ../../src:/app/src:rw
      - ../../pom.xml:/app/pom.xml:rw
      - maven-repo:/root/.m2
    ports:
      - "${APP_PORT:-8081}:8080"
      - "5005:5005"
    networks:
      - server-net

volumes:
  postgres_data:
  redis_data:
  maven-repo:

networks:
  server-net:
    driver: bridge